version: "3.9"

# This file serves as an example compose that sub-repos can leverage for orchestrating their local development
# environment.

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tunnelhop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
        - database:/var/lib/postgresql/data
    networks:
      - api-network

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - loki:/etc/loki
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - api-network

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - promtail:/etc/promtail
      - ./promtail/config.yml:/etc/promtail/config.yml
      - type: bind
        source: ./logs/api.log
        target: /etc/promtail/logs/api.log
    depends_on:
      - loki
    command: -config.file=/etc/promtail/config.yml
    networks:
      - api-network

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    build: './grafana'
    depends_on:
      - promtail
      - loki
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  database:
  grafana:
  promtail:
  loki: