server:
  http_listen_port: 8181
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: tunnelhop-api-logs
  static_configs:
  - targets:
    - localhost
    labels:
      job: tunnelhop-api-logs
      __path__: /etc/promtail/logs/*log
